# Site
title: DayuYu
subtitle: ''
description: 3D GIS, 3D City Modelling
keywords: 3D GIS, 3D City Modelling, 3D SDI, 3D GIService
author: DayuYu
language: en
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://dyuzz.github.io
root: /
